baseurl = "/"
languageCode = "en-US"
title = "Jolie Bourek"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/post/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Jolie Bourek"
  occupation = "Biology Student at the University of Texas at Austin"
  about = "I love science, nature, traveling, and music."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "joliemb"
  Email         = "joliebourek@gmail.com"
#  Twitter       = "username"
  LinkedIn      = "joliebourek"
#  Instagram     = "username"
#  Stackoverflow = "username"
#  Medium        = "username"
#  Telegram      = "username"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/post/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
